from setuptools import setup, find_packages

version = '0.0.1'

setup(name="helga",
      version=version,
      description=('IRC bot using twisted'),
      classifiers=['Development Status :: 1 - Beta',
                   'Environment :: IRC',
                   'Intended Audience :: Twisted Developers, IRC Bot Developers',
                   'License :: OSI Approved :: MIT License',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python',
                   'Topic :: Software Development :: Libraries :: Python Modules',
                   'Topic :: IRC Bots'],
      keywords='irc bot',
      author='Shaun Duncan',
      author_email='shaun.duncan@gmail.com',
      url='https://github.com/shaunduncan/helga',
      license='MIT',
      packages=find_packages(),
      entry_points = dict(
          helga_handlers = [
              'haiku = helga.extensions.haiku:HaikuExtension',
              'dubstep = helga.extensions.dubstep:DubstepExtension',
              'ascii_artz = helga.extensions.icanhazascii:ICanHazAsciiExtension',
              'fredoisms = helga.extensions.fredoism:FredoismExtension',
              'facts = helga.extensions.facts:FactExtension',
              'giphy = helga.extensions.giphy:GiphyExtension',
              'controls = helga.extensions.core:ControlExtension',
              'ignore = helga.extensions.core:IgnoreExtension',
              'help = helga.extensions.core:HelpExtension',
              'jira = helga.extensions.jira:JiraExtension',
              'loljava = helga.extensions.loljava:LOLJavaExtension',
              'meanttosay = helga.extensions.mts:MTSExtension',
              'no_more_olga = helga.extensions.no_more_olga:NoMoreOlgaExtension',
              'oneliner = helga.extensions.oneliner:OneLinerExtension',
              'oper = helga.extensions.operator:OperatorExtension',
              'reviewboard = helga.extensions.reviewboard:ReviewboardExtension',
              'stfu = helga.extensions.stfu:STFUExtension',
              'tanka = helga.extensions.tanka:TankaExtension',
              'wiki_whois = helga.extensions.wiki_whois:WikiWhoisExtension',
          ],
          console_scripts = [
              'helga = helga.run:run',
          ],
      ),
)
