[tox]
envlist = py38,py39,py310,py311,py312,flake8

[testenv]
deps =
    -r{toxinidir}/requirements.txt
    pytest
    mock
    pretend
    freezegun
    pytest-cov
    pytest-asyncio
sitepackages = False
setenv =
    HELGA_SETTINGS=
commands =
    py.test -q --cov helga --cov-report term-missing

[testenv:flake8]
deps =
    flake8
    flake8-docstrings
    flake8-import-order
skip_install = True
commands =
    flake8 helga

[testenv:docs]
deps =
    -r{toxinidir}/requirements.txt
    sphinx
    sphinx_rtd_theme
commands =
    sphinx-build -a -b html {toxinidir}/docs/source {toxinidir}/docs/build/html
